version: '3'
networks:
  app_network_compose:
    driver: bridge 
services:
  app:
    container_name: app
    build: .
    restart: unless-stopped
    networks:
      app_network_compose:
    ports:
    - "8080:8080"
